logging:
  level:
    root: INFO

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.graphql.GraphQlAutoConfiguration
  graphql:
    path: /fieldlab-woz/api
    graphiql:
      enabled: true
      path: /fieldlab-woz

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

orchestrate:
  mapping: config/mapping.yaml
  sources:
    bag:
      type: rest
      options:
        baseUrl: https://fds-gemeente-zonnendaal.apps.digilab.network/api

    woz:
      type: rest
      options:
        baseUrl: http://fds-fieldlab-fsc-outway.apps.digilab.network
        headers:
          Fsc-Grant-Hash: ${fsc_hash_woudendijk}
        paths:
          WOZObject: woz-objects
