objectTypes:
  Address:
    attributes:
      id:
        type: String
        identifier: true
        cardinality: 1
      street:
        type: String
        cardinality: 1
      houseNumber:
        type: Integer
        cardinality: 1
      houseNumberAddition:
        type: String
        cardinality: 0..1
      zipCode:
        type: String
        cardinality: 1
      municipality.name:
        type: String
        cardinality: 1
      municipality.code:
        type: String
        cardinality: 1
      purpose:
        type: String
        cardinality: 1
      surface:
        type: Integer
        cardinality: 1
      buildings[0].id:
        type: String
        cardinality: 0..1
      buildings[0].constructedAt:
        type: String
        cardinality: 0..1
    relations:
      buildings:
        target: Building
        cardinality: 0..*
        inverseName: Addresses
        inverseCardinality: 1

  Building:
    attributes:
      id:
        type: String
        identifier: true
        cardinality: 1
      constructedAt:
        type: String
        cardinality: 1
      surface:
        type: Integer
        cardinality: 0..1
    relations:
      addresses:
        target: Address
        cardinality: 0..*
        inverseName: building
        inverseCardinality: 1
