objectTypes:
  Address:
    attributes:
      id:
        type: String
        identifier: true
        cardinality: 1
      street:
        type: String
        cardinality: 1
      houseNumber:
        type: Integer
        cardinality: 1
      houseNumberAddition:
        type: String
        cardinality: 0..1
      zipCode:
        type: String
        cardinality: 1
      #      Municipality: TODO nested object
      purpose:
        type: String
        cardinality: 1
      surface:
        type: Integer
        cardinality: 1
    relations:
      buildings:
        target: Building
        cardinality: 0..*
        inverseName: Addresses
        inverseCardinality: 1

  Building:
    attributes:
      id:
        type: String
        identifier: true
        cardinality: 1
#      constructedAt:
#        type: DateTime
#        cardinality: 1
      surface:
        type: Integer
        cardinality: 0..1
      plots:
        type: String
        cardinality: 0..*
    relations:
      addresses:
        target: Address
        cardinality: 0..*
        inverseName: building
        inverseCardinality: 1 #?
