lineageNameMapping:
  hasLineage: geregistreerdMet
  ObjectLineage: Registratie
  orchestratedDataElements: bestaatUit
  OrchestratedDataElements: GeorkestreerdGegeven
  SourceDataElement: Brongegeven
  ObjectReference: Object
  subject: onderwerp
  property: kenmerk
  value: waarde
  objectKey: identificatie
  objectType: type
  wasDerivedFrom: isAfgeleidVan

targetModel:
  loader: yaml
  location: config/model.yaml

sourceModels:
  bag:
    loader: yaml
    location: config/bag.yaml
  woz:
    loader: yaml
    location: config/woz.yaml
  brp:
    loader: yaml
    location: config/brp.yaml

sourceRelations:
  - sourceType: woz:WOZObject
    property:
      name: heeftVerblijfsobject
      target: bag:Address
      cardinality: 1
      inverseName: isAdresVanWozObject
      inverseCardinality: 0..*
      keyMapping:
        id: addressableObjectId
  - sourceType: woz:WOZObject
    property:
      name: isVanPersoon
      target: brp:Person
      cardinality: 0..1
      inverseName: isEigenaarVan
      inverseCardinality: 0..*
      keyMapping:
        bsn: stakeholderOwner.burgerServiceNummer
  - sourceType: brp:Person
    property:
      name: heeftGeregistreerdAdres
      target: bag:Address
      cardinality: 1
      inverseName: isAdresVanPersoon
      inverseCardinality: 0..*
      keyMapping:
        id: registeredAddressId
  - sourceType: bag:Address
    property:
      name: heeftPand
      target: bag:Building
      cardinality: 0..1
      inverseName: isPandvanAdres
      inverseCardinality: 0..*
      keyMapping:
        id: buildings[0].id

objectTypeMappings:
  Beschikking:
    sourceRoot: woz:WOZObject
    propertyMappings:
      identificatie:
        pathMappings:
          path: id
      type:
        pathMappings:
          path: type
      isVoor:
        pathMappings:
          path: isVanPersoon

  Waarde:
    sourceRoot: woz:WOZObject
    propertyMappings:
      identificatie:
        pathMappings:
          path: values[0].id
      vastgesteldeWaarde:
        pathMapping:
          path: values[0].value
      waardepeildatum:
        pathMapping:
          path: values[0].valuationAt
          map:
            type: cel
            options:
              expr: 'string(timestamp(result).getDate())+"-"+string(timestamp(result).getMonth())+"-"+string(timestamp(result).getFullYear())'
      ingangsdatumWaarde:
        pathMapping:
          path: values[0].effectiveAt
          map:
            type: cel
            options:
              expr: 'string(timestamp(result).getFullYear())+"-"+string(timestamp(result).getMonth())+"-"+string(timestamp(result).getDate())'


  WozObject:
    sourceRoot: woz:WOZobject
    propertyMappings:
      wozObjectnummer:
        pathMappings:
          path: id
      typeWozObject:
        pathMappings:
          path: type
      ontleentAanduidingAan:
        pathMapping:
          path: heeftVerblijfsobject

  Verblijfsobject:
    sourceRoot: bag:Address
    propertyMappings:
      identificatie:
        pathMappings:
          path: id
      gebruiksdoel:
        pathMappings:
          path: purpose
      oppervlakte:
        pathMappings:
          path: surface
      maaktDeelUitVan:
        pathMappings:
          path: heeftPand

  Pand:
    sourceRoot: bag:Pand
    propertyMappings:
      identificatie:
        pathMappings:
          path: id
      totaaloppervlakte:
        pathMappings:
          path: surface
      oorspronkelijkBouwjaar:
        pathMappings:
          path: constructedAt
          map:
            type: cel
            options:
              expr: 'timestamp(result).getFullYear()'

  Adres:
    sourceRoot: bag:Address
    propertyMappings:
      identificatie:
        pathMappings:
          path: id
      straatnaam:
        pathMappings:
          path: street
      huisnummer:
        pathMappings:
          path: houseNumber
      huisnummertoevoeging:
        pathMappings:
          path: houseNumberAddition
      postcode:
        pathMappings:
          path: zipCode
      omschrijving:
        pathMappings:
          - path: street
          - path: houseNumber
            map:
              type: prepend
              options:
                prefix: ' '
          - path: houseNumberAddition
            map:
              type: prepend
              options:
                prefix: '-'
          - path: zipCode
            map:
              type: prepend
              options:
                prefix: ', '
          - path: municipality.name
            map:
              type: prepend
              options:
                prefix: ', Gemeente '
        combiner:
          type: join

  Gemeente:
    sourceRoot: bag:Address
    propertyMappings:
      code:
        pathMappings:
          path: municipality.code
      naam:
        pathMappings:
          path: municipality.name

  Persoon:
    sourceRoot: brp:Person
    propertyMappings:
      identificatie:
        pathMappings:
          path: id
      bsn:
        pathMappings:
          path: bsn
      naamAanschrijving:
        pathMappings:
          path: name
      geslachtsaanduiding:
        pathMappings:
          path: sex
      verblijftIn:
        pathMapping:
          path: heeftGeregistreerdAdres
      heeftBeschikking:
        pathMapping:
          path: isEigenaarVan