lineageNameMapping:
  hasLineage: geregistreerdMet
  ObjectLineage: Registratie
  orchestratedDataElements: bestaatUit
  OrchestratedDataElements: GeorkestreerdGegeven
  SourceDataElement: Brongegeven
  ObjectReference: Object
  subject: onderwerp
  property: kenmerk
  value: waarde
  objectKey: identificatie
  objectType: type
  wasDerivedFrom: isAfgeleidVan

targetModel:
  loader: yaml
  location: config/model.yaml

sourceModels:
  bag:
    loader: yaml
    location: config/bag.yaml
  woz:
    loader: yaml
    location: config/woz.yaml

objectTypeMappings:
  WozBeschikking:
    sourceRoot: woz:WOZObject
    propertyMappings:
      id:
        pathMappings:
          path: id
      type:
        pathMappings:
          path: type
