lineageNameMapping:
  hasLineage: geregistreerdMet
  ObjectLineage: Registratie
  orchestratedDataElements: bestaatUit
  OrchestratedDataElements: GeorkestreerdGegeven
  SourceDataElement: Brongegeven
  ObjectReference: Object
  subject: onderwerp
  property: kenmerk
  value: waarde
  objectKey: identificatie
  objectType: type
  wasDerivedFrom: isAfgeleidVan

targetModel:
  loader: yaml
  location: config/model.yaml

sourceModels:
  bag:
    loader: yaml
    location: config/bag.yaml
  woz:
    loader: yaml
    location: config/woz.yaml
  brp:
    loader: yaml
    location: config/brp.yaml

sourceRelations:
  - sourceType: woz:WOZObject
    property:
      name: heeftAlsAdres
      target: bag:Address
      cardinality: 1
      inverseName: isAdresVanWozObject
      inverseCardinality: 0..*
      keyMapping:
        id: addressableObjectId
  - sourceType: woz:WOZObject
    property:
      name: isVanPersoon
      target: brp:Person
      cardinality: 0..1
      inverseName: isEigenaarVan
      inverseCardinality: 0..*
      keyMapping:
        bsn: stakeholderOwner.burgerServiceNummer

objectTypeMappings:
  Beschikking:
    sourceRoot: woz:WOZObject
    propertyMappings:
      identificatie:
        pathMappings:
          path: id
      type:
        pathMappings:
          path: type
      adres:
        pathMappings:
          path: heeftAlsAdres
#      isVoorObject:
#        pathMappings:
#          path:
      isVoor:
        pathMappings:
          path: isVanPersoon

  Waarde:
    sourceRoot: woz:WOZObject
    propertyMappings:
      identificatie:
        pathMappings:
          path: values[0].id
      vastgesteldeWaarde:
        pathMapping:
          path: values[0].value

  Adres:
    sourceRoot: bag:Address
    propertyMappings:
      identificatie:
        pathMappings:
          path: id
      straatnaam:
        pathMappings:
          path: street

  Persoon:
    sourceRoot: brp:Person
    propertyMappings:
      identificatie:
        pathMappings:
          path: id
      bsn:
        pathMappings:
          path: bsn
      naamAanschrijving:
        pathMappings:
          path: name
      geslachtsaanduiding:
        pathMappings:
          path: sex
