objectTypes:
  Beschikking:
    attributes:
      identificatie:
        type: String
        identifier: true
        cardinality: 1
      type:
        type: String
        cardinality: 1
    relations:
      steltVast:
        target: Waarde
        cardinality: 1
        inverseName: isBeschiktMet
        inverseCardinality: 0..*
      isVoor:
        target: Persoon
        cardinality: 0..1
        inverseName: beschikkingVanPersoon
        inverseCardinality: 0..*
      #tijdelijk
      adres:
        target: Adres
        cardinality: 1
        inverseName: isAdresVan
        inverseCardinality: 0..*
  #      isVoorObject:
  #        target: WozObject
  #        cardinality: 1
  #        inverseName: heeftBeschikking
  #        inverseCardinality: 0..*

  Waarde:
    attributes:
      identificatie:
        type: String
        identifier: true
        cardinality: 1
      vastgesteldeWaarde:
        type: Integer
        cardinality: 1
#      waardePeildatum:
#        type: Date
#        cardinality: 1

  Adres:
    attributes:
      identificatie:
        type: String
        identifier: true
        cardinality: 1
      straatnaam:
        type: String
        cardinality: 1
  #      huisnummer:
  #        type: Integer
  #        cardinality: 1
  #      huisnummertoevoeging:
  #        type: String
  #        cardinality: 0..1
  #      postcode:
  #        type: String
  #        cardinality: 1
  #      #      gemeente: TODO nested object
  #      #      purpose:
  #      #        type: String
  #      #        cardinality: 1
  #      oppervlakte:
  #        type: Integer
  #        cardinality: 1

  Persoon:
    attributes:
      #      verantwoordelijkeGemeente:
      #        type: String
      #        cardinality: 1
      #      identificatieBRK:
      #        type: String
      #        cardinality: 0..*
      identificatie:
        type: String
        cardinality: 1
      bsn:
        type: String
        identifier: true
        cardinality: 1
      naamAanschrijving:
        type: String
        cardinality: 1
      geslachtsaanduiding:
        type: String
        cardinality: 1
