objectTypes:
  WOZObject:
    attributes:
      id:
        type: String
        identifier: true
        cardinality: 1
      addressableObjectId:
        type: String
        cardinality: 1
      stakeholderOwner.burgerServiceNummer:
        type: String
        cardinality: 1
      #      stakeholderOccupant: TODO Nested object
#        cardinality: 0..1
      values[0].id:
        type: String
        cardinality: 1
      values[0].wozObjectId:
        type: String
        cardinality: 1
      values[0].value:
        type: Integer
        cardinality: 1
      values[0].valuationAt:
        type: String
        cardinality: 1
      values[0].effectiveAt:
        type: String
        cardinality: 1
#      registeredPeople:
#        type: DateTime
#        cardinality: 1
      type:
        type: String # Enum: [residential, non-residential]
        cardinality: 1
#      createdAt:
#        type: DateTime
#        cardinality: 1
